# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spiCov <- function(S, n, r = NULL, verbose = FALSE) {
    .Call('spicov_spiCov', PACKAGE = 'spicov', S, n, r, verbose)
}

